title: "凌烟阁"
description: ""
url: 
baseurl: 
author: "凌烟阁主"
lang: "zh-CN"
paginate: 5
paginate_path: "/blog/page:num/"

markdown: kramdown
theme: jekyll-theme-mdui
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - node_modules