head: 
   favicon: "/assets/favicon/1.png" #  the favicon
   high_res_favicon: "/assets/favicon/1.png" #  the favicon using high quality format
   apple_touch_icon: "/assets/favicon/1.png" # the iOS Home button icon
   keywords: "" #  the site keywords

uiux:
   android_chrome_color: "#eeeeee" #  the color of the Chrome address bar
   nprogress_color: "#29d" #  the color of the top loading progress bar
   nprogress_buffer: 200 # the top loading progress bar buffers
   meng: true

background: 
   purecolor: "#eeeeee" # the background color

img: 
   avatar: "https://i.loli.net/2017/08/11/598d98437084d.jpg“" # your avatar

card: 
   card_shadow: 1 # card shadow (0-24), 0 is not displayed
   card_hoverable: false # When the hover to deepen the shadow
  
many_authors: false

sns_share: # SNS Share Switch
   twitter: true
   facebook: false
   googleplus: false
   weibo: true
   linkedin: false
   qq: true
   telegram: true

comment:
  used: "livere" # disqus,livere,gitment
  # disqus config
  disqus_shortname: "" # Your disqus 
  disqus_button: true # disqus load button
  disqus_proxy: false # # disqus proxy(Do not use)
  disqus_proxy_url: "" # (Do not use)
  disqus_api_key: "" # (Do not use)
  # livere config
  livere_type: 'city'
  livere_data_uid: 'MTAyMC8yOTM5MC81OTU4'
  # gitment config
  owner: ""
  repo: ""
  client_id: ""
  client_secret: ""
  
  
prism:
  themes: prism-okaidia
  components: 
    - bash 
    - apacheconf
  plugins: 

google_analytics: ""  # google analytics code

lang: "zh-CN"  # lang

deploy: "coding" # if you used coding pages
